### ISSUE TITLE
PHP Fatal error due to conflict with Active Campaign's plugin.

### ISSUE THREAD

**Issue by dgoldak** [easydigitaldownloads/edd-activecampaign#27]
PHP Fatal error: Cannot declare class ActiveCampaign, because the name is already in use in /home/s2/html/wp-content/plugins/edd-activecampaign/vendor/ActiveCampaign.class.php on line 112

Customer discovered a plugin conflict between the ActiveCampaign and EDD. The problem is that both are declaring `class ActiveCampaign` and that's creating a conflict. EDD's extension should seek to avoid conflicts by giving the class a unique name, like "EDDActiveCampaign," and maybe a unique name for AC_Connector (but I don't know whether there's a conflict there).

**Comment by dgoldak** [comment]
https://secure.helpscout.net/conversation/884299572/123577?folderId=180499

**Comment by dgoldak** [comment]
Another report of this error: https://secure.helpscout.net/conversation/900207090/124915/

I believe the conflict is with Restrict Content Pro - ActiveCampaign.

**Comment by cklosowski** [comment]
@nosegraze let's circle up and see if we can find a good solution here.

**Comment by nosegraze** [comment]
@cklosowski Hm I thought we'd fixed this problem here: https://github.com/easydigitaldownloads/edd-activecampaign/issues/20

**Comment by nosegraze** [comment]
I'm wondering if that second conflict was with the Gravity Forms ActiveCampaign add-on rather than the RCP one.

**Comment by mintplugins** [comment]
One simple workaround (that won't guarantee a fix in all cases) would be to hook to a higher priority on plugins_loaded. Another plugin might not do the "class_exists" check, so if we don't hook after them, they will still collide.

**Comment by dgoldak** [comment]
@nosegraze might be on to something. It appears the same issue happens with Ninja Forms - ActiveCampaign plugin:

```2019/11/01 16:34:20 [error] 43517#43517: *66490 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Cannot declare class ActiveCampaign, because the name is already in use in /var/www/edd.danielgoldak.com/htdocs/wp-content/plugins/edd-activecampaign/vendor/ActiveCampaign.class.php on line 0" while reading response header from upstream, client: 68.102.42.242, server: edd.danielgoldak.com, request: "POST /wp-admin/admin-ajax.php HTTP/2.0", upstream: "fastcgi://127.0.0.1:9000", host: "edd.danielgoldak.com", referrer: "https://edd.danielgoldak.com/checkout/"```

**Comment by mintplugins** [comment]
Looks like we may have just missed doing a class_exists check in the subscribe_email function, where the Active Campaign class is also being included.

**Comment by dgoldak** [comment]
Just confirmed that the error no longer occur with EDD ActivateCampaign + Ninja Forms ActiveCampaign + Stripe with `issue/27` loaded.
