### ISSUE TITLE
Add button to refresh lists

### ISSUE THREAD

**Issue by ashleyfae** [easydigitaldownloads/edd-activecampaign#39]
https://github.com/easydigitaldownloads/edd-activecampaign/issues/38 is going to introduce list caching. Once that's done, let's add a button in the admin area to force refresh the lists (break cache).

**Comment by ashleyfae** [comment]
@LisaCee This is going to have a few moving pieces to it so feel free to reach out to Robin or I for help.

Here's how I think we should do it:

1. We'll be adding a button wherever `get_lists()` is called (2 places). This button will say `Refresh Lists`.
1. The button should work via ajax. This means we'll need a JavaScript file. Here's a rough example of how to add one:
    - Hook into `admin_enqueue_scripts` action https://github.com/easydigitaldownloads/EDD-Commissions/blob/master/includes/scripts.php#L59
    - Use [wp_enqueue_script()](https://developer.wordpress.org/reference/functions/wp_enqueue_script/) to load it. Example: https://github.com/easydigitaldownloads/EDD-Commissions/blob/master/includes/scripts.php#L47 (This uses `wp_register_script()` but for our use case you can just change that to `wp_enqueue_script()`.
2. Clicking the button should make an ajax request. Example: https://github.com/easydigitaldownloads/EDD-Software-Licensing/blob/master/assets/js/edd-sl-admin.js#L20-L35
    - See [AJAX in Plugins](https://codex.wordpress.org/AJAX_in_Plugins#Ajax_on_the_Administration_Side)
    - We'll need to customize the `action` in the `data` object. (From [this line](https://github.com/easydigitaldownloads/EDD-Software-Licensing/blob/master/assets/js/edd-sl-admin.js#L25)) That's unique to our plugin and the action we're performing. For example: `edd_activecampaign_refresh_lists`.
    - The above linked example in SL also passes `data.license` and `data.download`. We don't need those. However, we should include a `nonce`. This can be a data attribute on the `<button>`. Use [wp_create_nonce()](https://developer.wordpress.org/reference/functions/wp_create_nonce/). The parameter is an action name. That can also be `edd_activecampaign_refresh_lists`. (It's a namespaced description of what action the nonce will be used for.)
    - We'll need to set up our AJAX callback in PHP. In the "AJAX in Plugins" article, see _"Then, set up a PHP function to handle the AJAX request."_
3. The AJAX callback.
    - This is responsible for actually refreshing and returning the lists.
    - We'll need to validate the nonce. You already did this in software licensing: https://github.com/easydigitaldownloads/EDD-Software-Licensing/blob/60c3d355f9423130df263bdc1b839f07ba86612a/includes/admin/license-actions.php#L562 However, instead of a `wp_die()` if it doesn't validate, call [wp_send_json_error()](https://developer.wordpress.org/reference/functions/wp_send_json_error/)
    - We'll also need [a permission check, again like you did in SL](https://github.com/easydigitaldownloads/EDD-Software-Licensing/blob/60c3d355f9423130df263bdc1b839f07ba86612a/includes/admin/license-actions.php#L557). But instead of `manage_licenses`, let's go with `edit_products`. Again, `wp_send_json_error()` if the permissions aren't met.
    - Then we have to [delete the transient](https://developer.wordpress.org/reference/functions/delete_transient/) (from the last PR).
    - Then call and return (via [wp_send_json_success](https://developer.wordpress.org/reference/functions/wp_send_json_success/)) `get_lists()`.
4. Formatting the AJAX response.
    - The AJAX response should replace the markup of lists that's already on the page, maintaining the same formatting and also maintaining whichever options might already be selected. For the one that outputs checkboxes, you might need to add a wrapper div around the checkboxes to easily replace that inner content.
    - `get_lists()` is used in two places: 1) [as a dropdown](https://github.com/easydigitaldownloads/edd-activecampaign/blob/release/1.1.2/edd-activecampaign.php#L500); and 2) [as a list of checkbox inputs](https://github.com/easydigitaldownloads/edd-activecampaign/blob/release/1.1.2/edd-activecampaign.php#L604-L609). So the JavaScript will need to re-populate those options differently depending on where it's called. How you do this is up to you. One option might be to add a `data` attribute to the plugin specifying which format to use (`data-format="checkbox"` and `data-format="dropdown"`). Or `data-context="settings"` and `data-context="download"` (where `settings` outputs a dropdown and `download` outputs a checkbox). :shrug: 
    - And, as mentioned, you should maintain whichever lists are already selected. Again, maybe a data attribute for this? `data-selected="{comma separated list IDs}"`

Example:

![Screenshot from 2021-06-15 10-18-18](https://user-images.githubusercontent.com/6324272/122027857-6020a100-cdc3-11eb-8a24-6ef67872b8dc.png)

After clicking the button, new option appears and existing list remains selected:

![Screenshot from 2021-06-15 10-19-15](https://user-images.githubusercontent.com/6324272/122027641-323b5c80-cdc3-11eb-9254-87cb82241050.png)

**Comment by LisaCee** [comment]
I'm so glad you added these screenshots because I was thinking of somewhere completely different. 

I am a bit daft, but where is this ActiveCampaign metabox? I've looked in 2.x and 3.0, payments/orders and customers. The only ActiveCampaign I am finding is in Settings but that is not a metabox like your example.

**Comment by ashleyfae** [comment]
> I'm so glad you added these screenshots because I was thinking of somewhere completely different.

What were you thinking? Maybe your idea is better!
