### ISSUE TITLE
Add per-product list subscription options

### ISSUE THREAD

**Issue by pippinsplugins** [easydigitaldownloads/edd-activecampaign#5]
Like our other email plugins, Active Campaign needs to support per-product list subscriptions.

**Comment by sunnyratilal** [comment]
PR opened at #16

**Comment by pippinsplugins** [comment]
@sunnyratilal The PR adds a drop down of lists in settings but I don't see anything for product-specific lists. Am I missing something?

**Comment by sunnyratilal** [comment]
Ah whoops - I missed that.

**Comment by sunnyratilal** [comment]
@pippinsplugins Ready for retesting
